SSOConfig:
    Default:
        SSORegion: us-east-1
        StartUrl: https://lnlp.awsapps.com/start
ConsoleDuration: 720
CacheRefresh: 168
UrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: "{{ .AccountAlias }}:{{ .RoleName }}"
FullTextSearch: true